"""engagement: notifications, community, check-ins, autoflow

Revision ID: 04bd84346011
Revises: 25b3dedf52ee
Create Date: 2026-09-26 22:26:09.802346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bd84346011'
down_revision: Union[str, Sequence[str], None] = '25b3dedf52ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autoflow_assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('autoflow_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('completed_step_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autoflow_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autoflow_assignments_autoflow_id'), ['autoflow_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_autoflow_assignments_client_id'), ['client_id'], unique=False)

    op.create_table('autoflows',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autoflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autoflows_coach_id'), ['coach_id'], unique=False)

    op.create_table('checkin_assignments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('frequency', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_notified_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_assignments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_assignments_form_id'), ['form_id'], unique=False)

    op.create_table('checkin_forms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkin_forms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_forms_coach_id'), ['coach_id'], unique=False)

    op.create_table('checkin_responses',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('assignment_id', sa.String(length=64), nullable=False),
    sa.Column('form_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('coach_comment', sa.Text(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'due_date', name='uq_checkin_responses_due')
    )
    with op.batch_alter_table('checkin_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_responses_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_responses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_responses_form_id'), ['form_id'], unique=False)

    op.create_table('community_groups',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_groups_coach_id'), ['coach_id'], unique=False)

    op.create_table('group_members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'client_id', name='uq_group_members')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_group_id'), ['group_id'], unique=False)

    op.create_table('group_messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_group_id'), ['group_id'], unique=False)

    op.create_table('group_posts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_posts_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_posts_group_id'), ['group_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.JSON(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('post_comments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comments_post_id'), ['post_id'], unique=False)

    op.create_table('post_likes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('post_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_likes')
    )
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_likes_post_id'), ['post_id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('stored_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_files_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_digest', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_digest')

    with op.batch_alter_table('stored_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_files_client_id'))

    op.drop_table('stored_files')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_likes_post_id'))

    op.drop_table('post_likes')
    with op.batch_alter_table('post_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comments_post_id'))

    op.drop_table('post_comments')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('group_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_posts_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_posts_created_at'))
        batch_op.drop_index(batch_op.f('ix_group_posts_author_user_id'))

    op.drop_table('group_posts')
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_messages_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_created_at'))

    op.drop_table('group_messages')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_client_id'))

    op.drop_table('group_members')
    with op.batch_alter_table('community_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_groups_coach_id'))

    op.drop_table('community_groups')
    with op.batch_alter_table('checkin_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_responses_form_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_responses_client_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_responses_assignment_id'))

    op.drop_table('checkin_responses')
    with op.batch_alter_table('checkin_forms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_forms_coach_id'))

    op.drop_table('checkin_forms')
    with op.batch_alter_table('checkin_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_assignments_form_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_assignments_client_id'))

    op.drop_table('checkin_assignments')
    with op.batch_alter_table('autoflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autoflows_coach_id'))

    op.drop_table('autoflows')
    with op.batch_alter_table('autoflow_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autoflow_assignments_client_id'))
        batch_op.drop_index(batch_op.f('ix_autoflow_assignments_autoflow_id'))

    op.drop_table('autoflow_assignments')
    # ### end Alembic commands ###
