"""training library and workout groups

Revision ID: 1458ce05d6cb
Revises: 19ff5c37fe2b
Create Date: 2026-09-26 18:00:08.257169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1458ce05d6cb'
down_revision: Union[str, Sequence[str], None] = '19ff5c37fe2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('exercises', sa.JSON(), nullable=False),
    sa.Column('groups', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_templates_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_templates_id'), ['id'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('tracking_type', sa.String(length=32), server_default='reps_weight', nullable=False))

    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), server_default='', nullable=False))
        batch_op.add_column(sa.Column('groups', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.drop_column('groups')
        batch_op.drop_column('description')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('tracking_type')
        batch_op.drop_column('video_url')

    with op.batch_alter_table('workout_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_templates_id'))
        batch_op.drop_index(batch_op.f('ix_workout_templates_coach_id'))

    op.drop_table('workout_templates')
    # ### end Alembic commands ###
