"""nutrition and habits

Revision ID: 25b3dedf52ee
Revises: 1458ce05d6cb
Create Date: 2026-09-26 18:45:05.120513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '25b3dedf52ee'
down_revision: Union[str, Sequence[str], None] = '1458ce05d6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_goals',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('rest_day_calories', sa.Float(), nullable=True),
    sa.Column('rest_day_protein', sa.Float(), nullable=True),
    sa.Column('rest_day_carbs', sa.Float(), nullable=True),
    sa.Column('rest_day_fat', sa.Float(), nullable=True),
    sa.Column('water_ml', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('custom_foods',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('servings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_foods_coach_id'), ['coach_id'], unique=False)

    op.create_table('daily_metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('water_ml', sa.Integer(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'date', name='uq_daily_metrics_client_date')
    )
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_metrics_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_metrics_date'), ['date'], unique=False)

    op.create_table('food_log_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('serving_label', sa.String(length=64), nullable=False),
    sa.Column('serving_grams', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('fiber', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_log_entries_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_log_entries_date'), ['date'], unique=False)

    op.create_table('habit_checkins',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('habit_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'date', name='uq_habit_checkins_habit_date')
    )
    with op.batch_alter_table('habit_checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_checkins_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_checkins_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_checkins_habit_id'), ['habit_id'], unique=False)

    op.create_table('habits',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habits_client_id'), ['client_id'], unique=False)

    op.create_table('meal_plan_assignments',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('meal_plan_id', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('meal_plan_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_assignments_meal_plan_id'), ['meal_plan_id'], unique=False)

    op.create_table('meal_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_coach_id'), ['coach_id'], unique=False)

    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_logs_client_id'))
        batch_op.drop_index(batch_op.f('ix_habit_logs_date'))
        batch_op.drop_index(batch_op.f('ix_habit_logs_id'))

    op.drop_table('habit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_logs',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date', sa.VARCHAR(length=32), nullable=False),
    sa.Column('habits', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_logs_client_id'), ['client_id'], unique=False)

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_coach_id'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('meal_plan_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_assignments_meal_plan_id'))

    op.drop_table('meal_plan_assignments')
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habits_client_id'))

    op.drop_table('habits')
    with op.batch_alter_table('habit_checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_checkins_habit_id'))
        batch_op.drop_index(batch_op.f('ix_habit_checkins_date'))
        batch_op.drop_index(batch_op.f('ix_habit_checkins_client_id'))

    op.drop_table('habit_checkins')
    with op.batch_alter_table('food_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_log_entries_date'))
        batch_op.drop_index(batch_op.f('ix_food_log_entries_client_id'))

    op.drop_table('food_log_entries')
    with op.batch_alter_table('daily_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_metrics_date'))
        batch_op.drop_index(batch_op.f('ix_daily_metrics_client_id'))

    op.drop_table('daily_metrics')
    with op.batch_alter_table('custom_foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_foods_coach_id'))

    op.drop_table('custom_foods')
    op.drop_table('client_goals')
    # ### end Alembic commands ###
