"""marketplace billing and admin

Revision ID: 2ce9ccfe3651
Revises: 04bd84346011
Create Date: 2026-09-26 23:28:23.720242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce9ccfe3651'
down_revision: Union[str, Sequence[str], None] = '04bd84346011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('billing', sa.String(length=16), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.String(length=64), nullable=True),
    sa.Column('autoflow_id', sa.String(length=64), nullable=True),
    sa.Column('onboarding_form_id', sa.String(length=64), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_coach_id'), ['coach_id'], unique=False)

    op.create_table('payment_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_requests_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_requests_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_requests_token'), ['token'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('subscription_id', sa.String(length=64), nullable=True),
    sa.Column('payment_request_id', sa.String(length=64), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('fees_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('fulfilled', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference'), ['reference'], unique=True)

    op.create_table('payout_accounts',
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('bank_code', sa.String(length=32), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_last4', sa.String(length=8), nullable=False),
    sa.Column('subaccount_code', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('coach_id'),
    sa.UniqueConstraint('subaccount_code')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('package_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_period_start', sa.Date(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('authorization_code', sa.String(length=64), nullable=True),
    sa.Column('card_label', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_package_id'), ['package_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_package_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_coach_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_client_id'))

    op.drop_table('subscriptions')
    op.drop_table('payout_accounts')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))
        batch_op.drop_index(batch_op.f('ix_payments_coach_id'))
        batch_op.drop_index(batch_op.f('ix_payments_client_id'))

    op.drop_table('payments')
    with op.batch_alter_table('payment_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_requests_token'))
        batch_op.drop_index(batch_op.f('ix_payment_requests_coach_id'))
        batch_op.drop_index(batch_op.f('ix_payment_requests_client_id'))

    op.drop_table('payment_requests')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_coach_id'))

    op.drop_table('packages')
    # ### end Alembic commands ###
