"""initial schema

Revision ID: 19ff5c37fe2b
Revises: 
Create Date: 2026-09-26 15:55:14.752370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ff5c37fe2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_feed',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_avatar', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_feed_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_feed_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_feed_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_feed_id'), ['id'], unique=False)

    op.create_table('clients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=False),
    sa.Column('experience_level', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.String(length=32), nullable=False),
    sa.Column('current_program_id', sa.String(length=64), nullable=True),
    sa.Column('current_program_name', sa.String(length=255), nullable=True),
    sa.Column('compliance_rate', sa.Float(), nullable=False),
    sa.Column('workouts_completed', sa.Integer(), nullable=False),
    sa.Column('total_workouts_assigned', sa.Integer(), nullable=False),
    sa.Column('last_active', sa.String(length=64), nullable=False),
    sa.Column('starting_weight_kg', sa.Float(), nullable=False),
    sa.Column('current_weight_kg', sa.Float(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=False),
    sa.Column('target_body_fat', sa.Float(), nullable=False),
    sa.Column('injuries_and_health', sa.JSON(), nullable=False),
    sa.Column('medical_alerts', sa.Text(), nullable=True),
    sa.Column('custom_coach_notes', sa.JSON(), nullable=False),
    sa.Column('onboarding_survey', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_status'), ['status'], unique=False)

    op.create_table('email_otps',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_otps_email'), ['email'], unique=False)

    op.create_table('exercises',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_muscle', sa.String(length=64), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.String(length=64), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('form_cues', sa.JSON(), nullable=False),
    sa.Column('demo_video_placeholder_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercises_primary_muscle'), ['primary_muscle'], unique=False)

    op.create_table('habit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('habits', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_logs_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_habit_logs_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    op.create_table('metrics',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('arms_cm', sa.Float(), nullable=True),
    sa.Column('thighs_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_metrics_id'), ['id'], unique=False)

    op.create_table('personal_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('estimated_1rm_kg', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('previous_weight_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_records_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_exercise_name'), ['exercise_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_id'), ['id'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('coach_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=64), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('assigned_client_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_coach_id'), ['coach_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_programs_title'), ['title'], unique=False)

    op.create_table('progress_photos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('view', sa.String(length=32), nullable=False),
    sa.Column('photo_url', sa.String(length=512), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_photos_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_photos_id'), ['id'], unique=False)

    op.create_table('scheduled_workouts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_avatar', sa.String(length=512), nullable=False),
    sa.Column('program_id', sa.String(length=64), nullable=True),
    sa.Column('program_name', sa.String(length=255), nullable=True),
    sa.Column('workout_day_id', sa.String(length=64), nullable=False),
    sa.Column('workout_title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('coach_feedback', sa.Text(), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=True),
    sa.Column('pr_count', sa.Integer(), nullable=True),
    sa.Column('exercises', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_workouts_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_client_id'))

    op.drop_table('users')
    with op.batch_alter_table('scheduled_workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_date'))
        batch_op.drop_index(batch_op.f('ix_scheduled_workouts_client_id'))

    op.drop_table('scheduled_workouts')
    with op.batch_alter_table('progress_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_photos_id'))
        batch_op.drop_index(batch_op.f('ix_progress_photos_date'))
        batch_op.drop_index(batch_op.f('ix_progress_photos_client_id'))

    op.drop_table('progress_photos')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_title'))
        batch_op.drop_index(batch_op.f('ix_programs_id'))
        batch_op.drop_index(batch_op.f('ix_programs_coach_id'))

    op.drop_table('programs')
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_records_id'))
        batch_op.drop_index(batch_op.f('ix_personal_records_exercise_name'))
        batch_op.drop_index(batch_op.f('ix_personal_records_date'))
        batch_op.drop_index(batch_op.f('ix_personal_records_client_id'))

    op.drop_table('personal_records')
    with op.batch_alter_table('metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_id'))
        batch_op.drop_index(batch_op.f('ix_metrics_date'))
        batch_op.drop_index(batch_op.f('ix_metrics_client_id'))

    op.drop_table('metrics')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_messages_client_id'))

    op.drop_table('messages')
    with op.batch_alter_table('habit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_habit_logs_date'))
        batch_op.drop_index(batch_op.f('ix_habit_logs_client_id'))

    op.drop_table('habit_logs')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_primary_muscle'))
        batch_op.drop_index(batch_op.f('ix_exercises_name'))
        batch_op.drop_index(batch_op.f('ix_exercises_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_equipment'))
        batch_op.drop_index(batch_op.f('ix_exercises_coach_id'))

    op.drop_table('exercises')
    with op.batch_alter_table('email_otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_otps_email'))

    op.drop_table('email_otps')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_status'))
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_id'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
        batch_op.drop_index(batch_op.f('ix_clients_coach_id'))

    op.drop_table('clients')
    with op.batch_alter_table('activity_feed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_feed_id'))
        batch_op.drop_index(batch_op.f('ix_activity_feed_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_feed_coach_id'))
        batch_op.drop_index(batch_op.f('ix_activity_feed_client_id'))

    op.drop_table('activity_feed')
    # ### end Alembic commands ###
